// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/escrow/v1/escrow.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateEscrowStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EscrowId      uint32                 `protobuf:"varint,1,opt,name=escrow_id,json=escrowId,proto3" json:"escrow_id,omitempty"`
	NewStatus     string                 `protobuf:"bytes,2,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"` // e.g., "Funded", "Released"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEscrowStatusRequest) Reset() {
	*x = UpdateEscrowStatusRequest{}
	mi := &file_proto_escrow_v1_escrow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEscrowStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEscrowStatusRequest) ProtoMessage() {}

func (x *UpdateEscrowStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_escrow_v1_escrow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEscrowStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateEscrowStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_escrow_v1_escrow_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateEscrowStatusRequest) GetEscrowId() uint32 {
	if x != nil {
		return x.EscrowId
	}
	return 0
}

func (x *UpdateEscrowStatusRequest) GetNewStatus() string {
	if x != nil {
		return x.NewStatus
	}
	return ""
}

type UpdateEscrowStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEscrowStatusResponse) Reset() {
	*x = UpdateEscrowStatusResponse{}
	mi := &file_proto_escrow_v1_escrow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEscrowStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEscrowStatusResponse) ProtoMessage() {}

func (x *UpdateEscrowStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_escrow_v1_escrow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEscrowStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateEscrowStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_escrow_v1_escrow_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateEscrowStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateEscrowStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetEscrowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EscrowId      uint32                 `protobuf:"varint,1,opt,name=escrow_id,json=escrowId,proto3" json:"escrow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEscrowRequest) Reset() {
	*x = GetEscrowRequest{}
	mi := &file_proto_escrow_v1_escrow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEscrowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEscrowRequest) ProtoMessage() {}

func (x *GetEscrowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_escrow_v1_escrow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEscrowRequest.ProtoReflect.Descriptor instead.
func (*GetEscrowRequest) Descriptor() ([]byte, []int) {
	return file_proto_escrow_v1_escrow_proto_rawDescGZIP(), []int{2}
}

func (x *GetEscrowRequest) GetEscrowId() uint32 {
	if x != nil {
		return x.EscrowId
	}
	return 0
}

type EscrowResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BuyerId            uint32                 `protobuf:"varint,2,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	SellerId           uint32                 `protobuf:"varint,3,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	Amount             float32                `protobuf:"fixed32,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Status             string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Conditions         string                 `protobuf:"bytes,6,opt,name=conditions,proto3" json:"conditions,omitempty"`
	BlockchainEscrowId uint32                 `protobuf:"varint,7,opt,name=blockchain_escrow_id,json=blockchainEscrowId,proto3" json:"blockchain_escrow_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EscrowResponse) Reset() {
	*x = EscrowResponse{}
	mi := &file_proto_escrow_v1_escrow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EscrowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscrowResponse) ProtoMessage() {}

func (x *EscrowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_escrow_v1_escrow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscrowResponse.ProtoReflect.Descriptor instead.
func (*EscrowResponse) Descriptor() ([]byte, []int) {
	return file_proto_escrow_v1_escrow_proto_rawDescGZIP(), []int{3}
}

func (x *EscrowResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EscrowResponse) GetBuyerId() uint32 {
	if x != nil {
		return x.BuyerId
	}
	return 0
}

func (x *EscrowResponse) GetSellerId() uint32 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

func (x *EscrowResponse) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *EscrowResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EscrowResponse) GetConditions() string {
	if x != nil {
		return x.Conditions
	}
	return ""
}

func (x *EscrowResponse) GetBlockchainEscrowId() uint32 {
	if x != nil {
		return x.BlockchainEscrowId
	}
	return 0
}

var File_proto_escrow_v1_escrow_proto protoreflect.FileDescriptor

const file_proto_escrow_v1_escrow_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/escrow/v1/escrow.proto\x12\tescrow.v1\"W\n" +
	"\x19UpdateEscrowStatusRequest\x12\x1b\n" +
	"\tescrow_id\x18\x01 \x01(\rR\bescrowId\x12\x1d\n" +
	"\n" +
	"new_status\x18\x02 \x01(\tR\tnewStatus\"P\n" +
	"\x1aUpdateEscrowStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"/\n" +
	"\x10GetEscrowRequest\x12\x1b\n" +
	"\tescrow_id\x18\x01 \x01(\rR\bescrowId\"\xda\x01\n" +
	"\x0eEscrowResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x19\n" +
	"\bbuyer_id\x18\x02 \x01(\rR\abuyerId\x12\x1b\n" +
	"\tseller_id\x18\x03 \x01(\rR\bsellerId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x02R\x06amount\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"conditions\x18\x06 \x01(\tR\n" +
	"conditions\x120\n" +
	"\x14blockchain_escrow_id\x18\a \x01(\rR\x12blockchainEscrowId2\xb1\x01\n" +
	"\rEscrowService\x12[\n" +
	"\fUpdateStatus\x12$.escrow.v1.UpdateEscrowStatusRequest\x1a%.escrow.v1.UpdateEscrowStatusResponse\x12C\n" +
	"\tGetEscrow\x12\x1b.escrow.v1.GetEscrowRequest\x1a\x19.escrow.v1.EscrowResponseB\x13Z\x11./proto/escrow/v1b\x06proto3"

var (
	file_proto_escrow_v1_escrow_proto_rawDescOnce sync.Once
	file_proto_escrow_v1_escrow_proto_rawDescData []byte
)

func file_proto_escrow_v1_escrow_proto_rawDescGZIP() []byte {
	file_proto_escrow_v1_escrow_proto_rawDescOnce.Do(func() {
		file_proto_escrow_v1_escrow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_escrow_v1_escrow_proto_rawDesc), len(file_proto_escrow_v1_escrow_proto_rawDesc)))
	})
	return file_proto_escrow_v1_escrow_proto_rawDescData
}

var file_proto_escrow_v1_escrow_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_escrow_v1_escrow_proto_goTypes = []any{
	(*UpdateEscrowStatusRequest)(nil),  // 0: escrow.v1.UpdateEscrowStatusRequest
	(*UpdateEscrowStatusResponse)(nil), // 1: escrow.v1.UpdateEscrowStatusResponse
	(*GetEscrowRequest)(nil),           // 2: escrow.v1.GetEscrowRequest
	(*EscrowResponse)(nil),             // 3: escrow.v1.EscrowResponse
}
var file_proto_escrow_v1_escrow_proto_depIdxs = []int32{
	0, // 0: escrow.v1.EscrowService.UpdateStatus:input_type -> escrow.v1.UpdateEscrowStatusRequest
	2, // 1: escrow.v1.EscrowService.GetEscrow:input_type -> escrow.v1.GetEscrowRequest
	1, // 2: escrow.v1.EscrowService.UpdateStatus:output_type -> escrow.v1.UpdateEscrowStatusResponse
	3, // 3: escrow.v1.EscrowService.GetEscrow:output_type -> escrow.v1.EscrowResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_escrow_v1_escrow_proto_init() }
func file_proto_escrow_v1_escrow_proto_init() {
	if File_proto_escrow_v1_escrow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_escrow_v1_escrow_proto_rawDesc), len(file_proto_escrow_v1_escrow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_escrow_v1_escrow_proto_goTypes,
		DependencyIndexes: file_proto_escrow_v1_escrow_proto_depIdxs,
		MessageInfos:      file_proto_escrow_v1_escrow_proto_msgTypes,
	}.Build()
	File_proto_escrow_v1_escrow_proto = out.File
	file_proto_escrow_v1_escrow_proto_goTypes = nil
	file_proto_escrow_v1_escrow_proto_depIdxs = nil
}
