# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: arbitrator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'arbitrator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61rbitrator.proto\".\n\x0b\x43hatMessage\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"f\n\x10MediationRequest\x12\x11\n\tescrow_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x1a\n\x04\x63hat\x18\x04 \x03(\x0b\x32\x0c.ChatMessage\"\xbb\x01\n\x0f\x44\x65\x63isionRequest\x12\x11\n\tescrow_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x02\x12\x10\n\x08\x62uyer_id\x18\x05 \x01(\t\x12\x11\n\tseller_id\x18\x06 \x01(\t\x12\x1a\n\x04\x63hat\x18\x07 \x03(\x0b\x32\x0c.ChatMessage\x12\x1f\n\x17\x64ispute_conditions_json\x18\x08 \x01(\t\"$\n\x11MediationResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\";\n\x10\x44\x65\x63isionResponse\x12\x10\n\x08\x64\x65\x63ision\x18\x01 \x01(\t\x12\x15\n\rjustification\x18\x02 \x01(\t2\x81\x01\n\x0c\x41IArbitrator\x12\x39\n\x10RequestMediation\x12\x11.MediationRequest\x1a\x12.MediationResponse\x12\x36\n\x0fRequestDecision\x12\x10.DecisionRequest\x1a\x11.DecisionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arbitrator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATMESSAGE']._serialized_start=20
  _globals['_CHATMESSAGE']._serialized_end=66
  _globals['_MEDIATIONREQUEST']._serialized_start=68
  _globals['_MEDIATIONREQUEST']._serialized_end=170
  _globals['_DECISIONREQUEST']._serialized_start=173
  _globals['_DECISIONREQUEST']._serialized_end=360
  _globals['_MEDIATIONRESPONSE']._serialized_start=362
  _globals['_MEDIATIONRESPONSE']._serialized_end=398
  _globals['_DECISIONRESPONSE']._serialized_start=400
  _globals['_DECISIONRESPONSE']._serialized_end=459
  _globals['_AIARBITRATOR']._serialized_start=462
  _globals['_AIARBITRATOR']._serialized_end=591
# @@protoc_insertion_point(module_scope)
