// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/auth/v0/auth.proto

package v0

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenRequest) Reset() {
	*x = VerifyTokenRequest{}
	mi := &file_proto_auth_v0_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenRequest) ProtoMessage() {}

func (x *VerifyTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v0_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v0_auth_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type VerifyTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenResponse) Reset() {
	*x = VerifyTokenResponse{}
	mi := &file_proto_auth_v0_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenResponse) ProtoMessage() {}

func (x *VerifyTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v0_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v0_auth_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyTokenResponse) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VerifyTokenResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *VerifyTokenResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            uint32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                  `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                  `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                  `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Activated     bool                    `protobuf:"varint,5,opt,name=activated,proto3" json:"activated,omitempty"`
	Version       int32                   `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	WalletAddress *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	AccountName   *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	AccountNumber *wrapperspb.StringValue `protobuf:"bytes,9,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	BankCode      *wrapperspb.Int32Value  `protobuf:"bytes,10,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_auth_v0_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v0_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_auth_v0_auth_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetActivated() bool {
	if x != nil {
		return x.Activated
	}
	return false
}

func (x *User) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *User) GetWalletAddress() *wrapperspb.StringValue {
	if x != nil {
		return x.WalletAddress
	}
	return nil
}

func (x *User) GetAccountName() *wrapperspb.StringValue {
	if x != nil {
		return x.AccountName
	}
	return nil
}

func (x *User) GetAccountNumber() *wrapperspb.StringValue {
	if x != nil {
		return x.AccountNumber
	}
	return nil
}

func (x *User) GetBankCode() *wrapperspb.Int32Value {
	if x != nil {
		return x.BankCode
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_proto_auth_v0_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v0_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v0_auth_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_proto_auth_v0_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v0_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v0_auth_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetUserResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CheckWalletAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress string                 `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckWalletAddressRequest) Reset() {
	*x = CheckWalletAddressRequest{}
	mi := &file_proto_auth_v0_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckWalletAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckWalletAddressRequest) ProtoMessage() {}

func (x *CheckWalletAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v0_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckWalletAddressRequest.ProtoReflect.Descriptor instead.
func (*CheckWalletAddressRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v0_auth_proto_rawDescGZIP(), []int{5}
}

func (x *CheckWalletAddressRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

type CheckWalletAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckWalletAddressResponse) Reset() {
	*x = CheckWalletAddressResponse{}
	mi := &file_proto_auth_v0_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckWalletAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckWalletAddressResponse) ProtoMessage() {}

func (x *CheckWalletAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v0_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckWalletAddressResponse.ProtoReflect.Descriptor instead.
func (*CheckWalletAddressResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v0_auth_proto_rawDescGZIP(), []int{6}
}

func (x *CheckWalletAddressResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *CheckWalletAddressResponse) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UpdateUserRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletAddress       string                 `protobuf:"bytes,2,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	EncryptedPrivateKey string                 `protobuf:"bytes,3,opt,name=encrypted_private_key,json=encryptedPrivateKey,proto3" json:"encrypted_private_key,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_proto_auth_v0_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v0_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v0_auth_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateUserRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *UpdateUserRequest) GetEncryptedPrivateKey() string {
	if x != nil {
		return x.EncryptedPrivateKey
	}
	return ""
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_proto_auth_v0_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v0_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v0_auth_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateUserResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_auth_v0_auth_proto protoreflect.FileDescriptor

const file_proto_auth_v0_auth_proto_rawDesc = "" +
	"\n" +
	"\x18proto/auth/v0/auth.proto\x12\aauth.v0\x1a\x1egoogle/protobuf/wrappers.proto\"*\n" +
	"\x12VerifyTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x82\x01\n" +
	"\x13VerifyTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\"\xa5\x03\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1c\n" +
	"\tactivated\x18\x05 \x01(\bR\tactivated\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x05R\aversion\x12C\n" +
	"\x0ewallet_address\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\rwalletAddress\x12?\n" +
	"\faccount_name\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\vaccountName\x12C\n" +
	"\x0eaccount_number\x18\t \x01(\v2\x1c.google.protobuf.StringValueR\raccountNumber\x128\n" +
	"\tbank_code\x18\n" +
	" \x01(\v2\x1b.google.protobuf.Int32ValueR\bbankCode\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"d\n" +
	"\x0fGetUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\x04user\x18\x02 \x01(\v2\r.auth.v0.UserR\x04user\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"B\n" +
	"\x19CheckWalletAddressRequest\x12%\n" +
	"\x0ewallet_address\x18\x01 \x01(\tR\rwalletAddress\"M\n" +
	"\x1aCheckWalletAddressResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\"\x87\x01\n" +
	"\x11UpdateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12%\n" +
	"\x0ewallet_address\x18\x02 \x01(\tR\rwalletAddress\x122\n" +
	"\x15encrypted_private_key\x18\x03 \x01(\tR\x13encryptedPrivateKey\"D\n" +
	"\x12UpdateUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xbb\x02\n" +
	"\vAuthService\x12H\n" +
	"\vVerifyToken\x12\x1b.auth.v0.VerifyTokenRequest\x1a\x1c.auth.v0.VerifyTokenResponse\x12<\n" +
	"\aGetUser\x12\x17.auth.v0.GetUserRequest\x1a\x18.auth.v0.GetUserResponse\x12]\n" +
	"\x12CheckWalletAddress\x12\".auth.v0.CheckWalletAddressRequest\x1a#.auth.v0.CheckWalletAddressResponse\x12E\n" +
	"\n" +
	"UpdateUser\x12\x1a.auth.v0.UpdateUserRequest\x1a\x1b.auth.v0.UpdateUserResponseB\x11Z\x0f./proto/auth/v0b\x06proto3"

var (
	file_proto_auth_v0_auth_proto_rawDescOnce sync.Once
	file_proto_auth_v0_auth_proto_rawDescData []byte
)

func file_proto_auth_v0_auth_proto_rawDescGZIP() []byte {
	file_proto_auth_v0_auth_proto_rawDescOnce.Do(func() {
		file_proto_auth_v0_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auth_v0_auth_proto_rawDesc), len(file_proto_auth_v0_auth_proto_rawDesc)))
	})
	return file_proto_auth_v0_auth_proto_rawDescData
}

var file_proto_auth_v0_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_auth_v0_auth_proto_goTypes = []any{
	(*VerifyTokenRequest)(nil),         // 0: auth.v0.VerifyTokenRequest
	(*VerifyTokenResponse)(nil),        // 1: auth.v0.VerifyTokenResponse
	(*User)(nil),                       // 2: auth.v0.User
	(*GetUserRequest)(nil),             // 3: auth.v0.GetUserRequest
	(*GetUserResponse)(nil),            // 4: auth.v0.GetUserResponse
	(*CheckWalletAddressRequest)(nil),  // 5: auth.v0.CheckWalletAddressRequest
	(*CheckWalletAddressResponse)(nil), // 6: auth.v0.CheckWalletAddressResponse
	(*UpdateUserRequest)(nil),          // 7: auth.v0.UpdateUserRequest
	(*UpdateUserResponse)(nil),         // 8: auth.v0.UpdateUserResponse
	(*wrapperspb.StringValue)(nil),     // 9: google.protobuf.StringValue
	(*wrapperspb.Int32Value)(nil),      // 10: google.protobuf.Int32Value
}
var file_proto_auth_v0_auth_proto_depIdxs = []int32{
	9,  // 0: auth.v0.User.wallet_address:type_name -> google.protobuf.StringValue
	9,  // 1: auth.v0.User.account_name:type_name -> google.protobuf.StringValue
	9,  // 2: auth.v0.User.account_number:type_name -> google.protobuf.StringValue
	10, // 3: auth.v0.User.bank_code:type_name -> google.protobuf.Int32Value
	2,  // 4: auth.v0.GetUserResponse.user:type_name -> auth.v0.User
	0,  // 5: auth.v0.AuthService.VerifyToken:input_type -> auth.v0.VerifyTokenRequest
	3,  // 6: auth.v0.AuthService.GetUser:input_type -> auth.v0.GetUserRequest
	5,  // 7: auth.v0.AuthService.CheckWalletAddress:input_type -> auth.v0.CheckWalletAddressRequest
	7,  // 8: auth.v0.AuthService.UpdateUser:input_type -> auth.v0.UpdateUserRequest
	1,  // 9: auth.v0.AuthService.VerifyToken:output_type -> auth.v0.VerifyTokenResponse
	4,  // 10: auth.v0.AuthService.GetUser:output_type -> auth.v0.GetUserResponse
	6,  // 11: auth.v0.AuthService.CheckWalletAddress:output_type -> auth.v0.CheckWalletAddressResponse
	8,  // 12: auth.v0.AuthService.UpdateUser:output_type -> auth.v0.UpdateUserResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_auth_v0_auth_proto_init() }
func file_proto_auth_v0_auth_proto_init() {
	if File_proto_auth_v0_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auth_v0_auth_proto_rawDesc), len(file_proto_auth_v0_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auth_v0_auth_proto_goTypes,
		DependencyIndexes: file_proto_auth_v0_auth_proto_depIdxs,
		MessageInfos:      file_proto_auth_v0_auth_proto_msgTypes,
	}.Build()
	File_proto_auth_v0_auth_proto = out.File
	file_proto_auth_v0_auth_proto_goTypes = nil
	file_proto_auth_v0_auth_proto_depIdxs = nil
}
