// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: ai-arbitrator/v1/arbitrator.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIArbitrator_RequestMediation_FullMethodName = "/ai_arbitrator.v1.AIArbitrator/RequestMediation"
	AIArbitrator_RequestDecision_FullMethodName  = "/ai_arbitrator.v1.AIArbitrator/RequestDecision"
)

// AIArbitratorClient is the client API for AIArbitrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Defines the AI Arbitrator service with two methods
type AIArbitratorClient interface {
	// A method to request AI-powered chat mediation
	RequestMediation(ctx context.Context, in *MediationRequest, opts ...grpc.CallOption) (*MediationResponse, error)
	// A method to request a final, binding AI decision
	RequestDecision(ctx context.Context, in *DecisionRequest, opts ...grpc.CallOption) (*DecisionResponse, error)
}

type aIArbitratorClient struct {
	cc grpc.ClientConnInterface
}

func NewAIArbitratorClient(cc grpc.ClientConnInterface) AIArbitratorClient {
	return &aIArbitratorClient{cc}
}

func (c *aIArbitratorClient) RequestMediation(ctx context.Context, in *MediationRequest, opts ...grpc.CallOption) (*MediationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MediationResponse)
	err := c.cc.Invoke(ctx, AIArbitrator_RequestMediation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIArbitratorClient) RequestDecision(ctx context.Context, in *DecisionRequest, opts ...grpc.CallOption) (*DecisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecisionResponse)
	err := c.cc.Invoke(ctx, AIArbitrator_RequestDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIArbitratorServer is the server API for AIArbitrator service.
// All implementations must embed UnimplementedAIArbitratorServer
// for forward compatibility.
//
// Defines the AI Arbitrator service with two methods
type AIArbitratorServer interface {
	// A method to request AI-powered chat mediation
	RequestMediation(context.Context, *MediationRequest) (*MediationResponse, error)
	// A method to request a final, binding AI decision
	RequestDecision(context.Context, *DecisionRequest) (*DecisionResponse, error)
	mustEmbedUnimplementedAIArbitratorServer()
}

// UnimplementedAIArbitratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIArbitratorServer struct{}

func (UnimplementedAIArbitratorServer) RequestMediation(context.Context, *MediationRequest) (*MediationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestMediation not implemented")
}
func (UnimplementedAIArbitratorServer) RequestDecision(context.Context, *DecisionRequest) (*DecisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestDecision not implemented")
}
func (UnimplementedAIArbitratorServer) mustEmbedUnimplementedAIArbitratorServer() {}
func (UnimplementedAIArbitratorServer) testEmbeddedByValue()                      {}

// UnsafeAIArbitratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIArbitratorServer will
// result in compilation errors.
type UnsafeAIArbitratorServer interface {
	mustEmbedUnimplementedAIArbitratorServer()
}

func RegisterAIArbitratorServer(s grpc.ServiceRegistrar, srv AIArbitratorServer) {
	// If the following call pancis, it indicates UnimplementedAIArbitratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIArbitrator_ServiceDesc, srv)
}

func _AIArbitrator_RequestMediation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MediationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIArbitratorServer).RequestMediation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIArbitrator_RequestMediation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIArbitratorServer).RequestMediation(ctx, req.(*MediationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIArbitrator_RequestDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIArbitratorServer).RequestDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIArbitrator_RequestDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIArbitratorServer).RequestDecision(ctx, req.(*DecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIArbitrator_ServiceDesc is the grpc.ServiceDesc for AIArbitrator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIArbitrator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai_arbitrator.v1.AIArbitrator",
	HandlerType: (*AIArbitratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestMediation",
			Handler:    _AIArbitrator_RequestMediation_Handler,
		},
		{
			MethodName: "RequestDecision",
			Handler:    _AIArbitrator_RequestDecision_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai-arbitrator/v1/arbitrator.proto",
}
